export const LOGIN_URL = 'http://localhost:8000/api/v1/jwt/login/'
export const IS_DEV = true
export const TIME_IN_MILLIS_REFRESH_NOTIFICATIONS = 60000
export const TIME_IN_MILLIS_REFRESH_MESSAGES = 5000
export const TIME_IN_MILLIS_REFRESH_MESSAGES_HEADER = 5000
export const TIME_IN_MILLIS_REFRESH_CONVERSATION_MESSAGES = 5000
