export const IS_DEV = false
export const TIME_IN_MILLIS_REFRESH_NOTIFICATIONS = 60000
export const TIME_IN_MILLIS_REFRESH_MESSAGES = 15000
export const TIME_IN_MILLIS_REFRESH_MESSAGES_HEADER = 15000
export const TIME_IN_MILLIS_REFRESH_CONVERSATION_MESSAGES = 15000
